### ISSUE TITLE
Disabled HTTP if TLS is enabled?

### ISSUE THREAD

**Issue by briandowns** [briandowns/simple-httpd#14]

**Comment by tidwall** [comment]
I would do a 301 redirect. I think this makes for a better experience.

**Comment by briandowns** [comment]
Good call. Currently both endpoints respond.

**Comment by briandowns** [comment]
Disabled for the time being. Only TLS via Let's Encrypt is run if specified. Only self signed certificate responds if specified.  Will look at 301's for another release.
