### ISSUE TITLE
Limit `make install` to produce the binary only for the current OS

### ISSUE THREAD

**Issue by ideahitme** [briandowns/simple-httpd#19]
Running `make install` triggers `go build` for every possible OS. This should probably be limited only for the OS where the command is invoked. 

Additionally, `./build.sh release`  rebuilds all binaries twice, because the check `[ $1 == "release" ]; `  is happening twice

**Comment by briandowns** [comment]
Thanks for filing this issue. I'll take a look this evening.

**Comment by briandowns** [comment]
Resolved in #20
